name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/finance-tracker .
        docker push ${{ secrets.DOCKER_USERNAME }}/finance-tracker

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Create PEM file
      run: |
        echo "${{ secrets.AWS_KEY }}" > key.pem
        chmod 400 key.pem

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -tt -i key.pem ec2-user@${{ secrets.AWS_IP }} << EOF
        echo "Killing any processes using port 80..."
        sudo fuser -k 80/tcp || true
        sleep 5  # Allow time for processes to terminate

        echo "Stopping any existing Docker containers..."
        docker stop finance-tracker || true
        docker rm finance-tracker || true

        echo "Pruning unused containers and networks..."
        docker container prune -f
        docker network prune -f

        echo "Pulling the latest image from Docker Hub..."
        docker pull ${{ secrets.DOCKER_USERNAME }}/finance-tracker:latest

        echo "Running the new Docker container on port 80..."
        docker run -d --name finance-tracker -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/finance-tracker:latest

        echo "Verifying that the Docker container is running..."
        docker ps

        echo "Check container logs to ensure it's running correctly..."
        docker logs finance-tracker
        EOF
