name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/finance-tracker .
        docker push ${{ secrets.DOCKER_USERNAME }}/finance-tracker

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 1: Create the .pem file from the secret
    - name: Create PEM file
      run: |
        echo "${{ secrets.AWS_KEY }}" > key.pem
        chmod 400 key.pem

    # Step 2: SSH into EC2 and deploy the app
    - name: Deploy to AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_IP }} << EOF
        echo "Stopping any processes using port 80..."
        sudo fuser -k 80/tcp || true

        echo "Stopping any running Docker containers..."
        docker stop \$(docker ps -q) || true

        echo "Removing any stopped Docker containers..."
        docker rm \$(docker ps -a -q) || true

        echo "Pruning unused Docker resources..."
        docker system prune -f

        echo "Pulling the latest Docker image from Docker Hub..."
        docker pull ${{ secrets.DOCKER_USERNAME }}/finance-tracker:latest

        echo "Running the new Docker container on port 80..."
        docker run -d --name finance-tracker -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/finance-tracker:latest
        EOF
